### ISSUE TITLE
Add support for basic views (e.g. EditText)

### ISSUE THREAD

**Issue by forkch** [frankiesardo/icepick#29]
It would be a very nice addition to be able to place the @Icicle annotation on basic views like EditText, Spinner, ... and their state would be saved / restored to/from the bundle.

**Comment by denley** [comment]
I think that this is a great idea. Quite often you want some view states to persist (text in EditText, checked state in a CheckBox or Switch, or the scroll position of a ScrollView or ListView).

Having to subclass each widget in order to save the state just adds more boilerplate, which defeats the purpose of this library.

**Comment by frankiesardo** [comment]
I'm not sure what you mean. Basic views already save their state (scroll position, text etc.) in the bundle on save instance state
